# Generated by Django 4.1.3 on 2022-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_readtime_alter_category_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='readtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
