# Generated by Django 4.1.3 on 2022-11-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_readtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='readtime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
